### ISSUE TITLE
Add input grabber to GUI

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#186]
We should move away from #184, as it is reliant on having a terminal window focused. Once we have our GUI working, it needs to be a priority to re-implement the keyboard input grabber to be part of the GUI process, we don't want to have the terminal focused while we have a full-screen GUI.

**Comment by steph-lheureux** [comment]
## TODO
- [ ] Add [.get_subscription_count()](https://docs.ros2.org/foxy/api/rclpy/api/topics.html#rclpy.publisher.Publisher.get_subscription_count) to `keystroke` publisher to make sure we are not publishing for no reason (check if the number of subscribers is greater than zero).
- [x] Convert ascii keystrokes to strings 
- [x] Update parameters for throttle curves
