### ISSUE TITLE
robot core functionality

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#53]
the robot needs core functionality before we can start testing it physically

Drive Functionality
- [x] xbox controller input on deck box (or devkit) #44
- [x] translate xbox input to twist messages #44
- [x] translate twist messages to throttle values for each thruster #26
- [x] use throttle values to control motors #25

Claw Functionality
- [x] read xbox controller inputs and publish bool for each of the 3 solenoids #54
- [x] Determine control schema for solenoids #54 
- [x] use bool to control solenoids #52

camera functionality
- [x] camera(s) read by video 4 linux #28
- [x] camera publisher operating #27
- [x] able to view camera(s) in rqt or rviz #27
